import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useParams } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import { ApiError, apiFetch } from '../api/client'
import type { WeeklyReportDetail } from '../api/types'
import ErrorMessage from '../components/ErrorMessage'
import Layout from '../components/Layout'
import { TopBar } from '../components/halo'
import LoadingSpinner from '../components/LoadingSpinner'

const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/

// Where the back-link / not-found CTA returns to — the Trends Recap tab,
// which is the weekly-reports list this detail page is opened from.
const RECAP_LIST_PATH = '/trends?tab=recap'

/**
 * URL whitelist for markdown links. ``react-markdown`` v9 ships a default
 * sanitiser that already filters obvious dangerous schemes, but we narrow
 * it explicitly: the weekly content_md is generated by Claude and only
 * ever needs http(s) and mailto links. Anything else (``javascript:``,
 * ``data:``, ``file:``, custom schemes) becomes an empty href so the link
 * still renders as text but isn't clickable. Defence in depth — model
 * output is treated as untrusted by default, even though Claude has
 * never been observed to emit malicious URLs in practice.
 */
function safeUrlTransform(url: string): string {
  return /^(https?:|mailto:)/i.test(url) ? url : ''
}

function formatWeekRange(isoMonday: string, locale: string): string {
  // Parse + format in UTC to dodge the TZ-shift bug: ``Intl.DateTimeFormat``
  // defaults to the user's local TZ — without the explicit ``timeZone: 'UTC'``
  // option, a Monday parsed at 00:00 UTC would render as the preceding Sunday
  // for users west of UTC.
  const monday = new Date(`${isoMonday}T00:00:00Z`)
  const sunday = new Date(monday)
  sunday.setUTCDate(monday.getUTCDate() + 6)
  const fmt = new Intl.DateTimeFormat(locale, {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  })
  return `${fmt.format(monday)} — ${fmt.format(sunday)}`
}

/**
 * Single weekly report rendered from the DB archive.
 *
 * Reached by tapping a card in the Dashboard Recap tab (or the weekly-report
 * Telegram message button). A missing or malformed week surfaces the
 * empty-state with a back-to-list CTA rather than a hard error.
 */
export default function WeeklyReport() {
  const { weekStart = '' } = useParams<{ weekStart: string }>()
  const { t, i18n } = useTranslation()
  const [data, setData] = useState<WeeklyReportDetail | null>(null)
  const [loading, setLoading] = useState(true)
  // ``notFound`` and ``error`` are deliberately separate states. 404 is the
  // expected outcome for a week with no report — render the empty-state.
  // Anything else is a hard error and gets the standard ErrorMessage treatment.
  const [notFound, setNotFound] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const validIso = useMemo(() => ISO_DATE_RE.test(weekStart), [weekStart])

  useEffect(() => {
    if (!validIso) {
      // Malformed URL — treat as not-found rather than firing the API call
      // (which would 422). Keeps the empty-state render consistent.
      // ``setError(null)`` ensures the not-found and error states stay
      // mutually exclusive: navigating from a previously-errored week to a
      // malformed URL would otherwise render BOTH the error banner and the
      // not-found CTA at once.
      setLoading(false)
      setNotFound(true)
      setData(null)
      setError(null)
      return
    }

    let cancelled = false
    setLoading(true)
    setNotFound(false)
    setError(null)
    setData(null)
    apiFetch<WeeklyReportDetail>(`/api/weekly-reports/${weekStart}`)
      .then(resp => {
        if (cancelled) return
        setData(resp)
      })
      .catch(err => {
        if (cancelled) return
        if (err instanceof ApiError && err.status === 404) {
          setNotFound(true)
        } else {
          setError(err instanceof Error ? err.message : t('weekly.error_load'))
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [weekStart])

  return (
    <Layout backTo={RECAP_LIST_PATH} backLabel={t('weekly.back_to_list')}>
      <div className="-mx-4 -mt-4 md:-mb-8 min-h-screen bg-halo-bg px-4 md:px-9 font-sans text-halo-ink">
      <TopBar title={validIso ? formatWeekRange(weekStart, i18n.language) : weekStart} />

      {loading && <LoadingSpinner />}

      {!loading && error && <ErrorMessage message={error} />}

      {!loading && notFound && (
        <div className="text-center py-12">
          <p className="text-halo-ink-dim text-sm mb-4">{t('weekly.not_found')}</p>
          <Link
            to={RECAP_LIST_PATH}
            className="inline-block px-4 py-2 rounded-chip bg-halo-surface border border-halo-border text-sm text-halo-ink no-underline hover:bg-halo-surface-2 transition-colors"
          >
            {t('weekly.back_to_list')}
          </Link>
        </div>
      )}

      {!loading && !error && !notFound && data && (
        <article className="bg-halo-surface border border-halo-border rounded-card p-5 mt-3">
          {/* Tailwind `prose` would be ideal here but the project doesn't ship
              the typography plugin — apply styling per-element via component
              overrides. Same approach as the chat-output formatter. */}
          <div className="weekly-md text-[14px] leading-relaxed text-halo-ink">
            <ReactMarkdown
              urlTransform={safeUrlTransform}
              components={{
                h1: props => <h2 className="text-base font-semibold mt-4 mb-2" {...props} />,
                h2: props => <h3 className="text-base font-semibold mt-4 mb-2" {...props} />,
                h3: props => <h4 className="text-sm font-semibold mt-3 mb-2" {...props} />,
                p: props => <p className="mb-3" {...props} />,
                ul: props => <ul className="list-disc pl-5 mb-3 space-y-1" {...props} />,
                ol: props => <ol className="list-decimal pl-5 mb-3 space-y-1" {...props} />,
                li: props => <li className="leading-snug" {...props} />,
                strong: props => <strong className="font-semibold" {...props} />,
                em: props => <em className="italic" {...props} />,
                hr: () => <hr className="my-4 border-halo-border" />,
                code: props => (
                  <code className="bg-halo-surface-2 rounded px-1 py-0.5 text-[12px]" {...props} />
                ),
                a: props => (
                  <a className="text-halo-brand underline" target="_blank" rel="noopener noreferrer" {...props} />
                ),
              }}
            >
              {data.content_md}
            </ReactMarkdown>
          </div>
        </article>
      )}
      </div>
    </Layout>
  )
}
