"""Add power_zone_names to athlete_settings

Revision ID: 0215d277ccb3
Revises: c6103f687387
Create Date: 2026-04-16 20:07:29.162558

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0215d277ccb3"
down_revision: Union[str, None] = "c6103f687387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("athlete_settings", sa.Column("power_zone_names", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athlete_settings", "power_zone_names")
    # ### end Alembic commands ###
