"""Add scheduled_workouts table

Revision ID: 109064c8f4df
Revises: 1530c62c3505
Create Date: 2026-03-24 05:37:27.242079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "109064c8f4df"
down_revision: Union[str, None] = "1530c62c3505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date_local", sa.String(), nullable=False),
        sa.Column("end_date_local", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("moving_time", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("workout_doc", sa.JSON(), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scheduled_workouts")
    # ### end Alembic commands ###
