"""Initial wellness hrv_analysis rhr_analysis tables

Revision ID: 1530c62c3505
Revises:
Create Date: 2026-03-23 18:57:45.945702

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1530c62c3505"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wellness",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ctl", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("ramp_rate", sa.Float(), nullable=True),
        sa.Column("ctl_load", sa.Float(), nullable=True),
        sa.Column("atl_load", sa.Float(), nullable=True),
        sa.Column("sport_info", sa.JSON(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("hrv", sa.Float(), nullable=True),
        sa.Column("sleep_secs", sa.Integer(), nullable=True),
        sa.Column("sleep_score", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("body_fat", sa.Float(), nullable=True),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ess_today", sa.Float(), nullable=True),
        sa.Column("banister_recovery", sa.Float(), nullable=True),
        sa.Column("recovery_score", sa.Float(), nullable=True),
        sa.Column("recovery_category", sa.String(), nullable=True),
        sa.Column("recovery_recommendation", sa.String(), nullable=True),
        sa.Column("readiness_score", sa.Integer(), nullable=True),
        sa.Column("readiness_level", sa.String(), nullable=True),
        sa.Column("ai_recommendation", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hrv_analysis",
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rmssd_7d", sa.Float(), nullable=True),
        sa.Column("rmssd_sd_7d", sa.Float(), nullable=True),
        sa.Column("rmssd_60d", sa.Float(), nullable=True),
        sa.Column("rmssd_sd_60d", sa.Float(), nullable=True),
        sa.Column("lower_bound", sa.Float(), nullable=True),
        sa.Column("upper_bound", sa.Float(), nullable=True),
        sa.Column("cv_7d", sa.Float(), nullable=True),
        sa.Column("swc", sa.Float(), nullable=True),
        sa.Column("days_available", sa.Integer(), nullable=False),
        sa.Column("trend_direction", sa.String(), nullable=True),
        sa.Column("trend_slope", sa.Float(), nullable=True),
        sa.Column("trend_r_squared", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date"],
            ["wellness.id"],
        ),
        sa.PrimaryKeyConstraint("date", "algorithm"),
    )
    op.create_table(
        "rhr_analysis",
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rhr_today", sa.Float(), nullable=True),
        sa.Column("rhr_7d", sa.Float(), nullable=True),
        sa.Column("rhr_sd_7d", sa.Float(), nullable=True),
        sa.Column("rhr_30d", sa.Float(), nullable=True),
        sa.Column("rhr_sd_30d", sa.Float(), nullable=True),
        sa.Column("rhr_60d", sa.Float(), nullable=True),
        sa.Column("rhr_sd_60d", sa.Float(), nullable=True),
        sa.Column("lower_bound", sa.Float(), nullable=True),
        sa.Column("upper_bound", sa.Float(), nullable=True),
        sa.Column("cv_7d", sa.Float(), nullable=True),
        sa.Column("days_available", sa.Integer(), nullable=False),
        sa.Column("trend_direction", sa.String(), nullable=True),
        sa.Column("trend_slope", sa.Float(), nullable=True),
        sa.Column("trend_r_squared", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date"],
            ["wellness.id"],
        ),
        sa.PrimaryKeyConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rhr_analysis")
    op.drop_table("hrv_analysis")
    op.drop_table("wellness")
    # ### end Alembic commands ###
