"""add_race_fields_and_table

Revision ID: 6c5f6ae05c97
Revises: 6e99dae5f51e
Create Date: 2026-04-12 18:04:13.608113

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c5f6ae05c97"
down_revision: Union[str, None] = "6e99dae5f51e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("race_type", sa.String(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("finish_time_sec", sa.Integer(), nullable=True),
        sa.Column("goal_time_sec", sa.Integer(), nullable=True),
        sa.Column("placement", sa.Integer(), nullable=True),
        sa.Column("placement_total", sa.Integer(), nullable=True),
        sa.Column("placement_ag", sa.String(), nullable=True),
        sa.Column("surface", sa.String(), nullable=True),
        sa.Column("weather", sa.String(), nullable=True),
        sa.Column("elevation_gain_m", sa.Float(), nullable=True),
        sa.Column("race_day_ctl", sa.Float(), nullable=True),
        sa.Column("race_day_atl", sa.Float(), nullable=True),
        sa.Column("race_day_tsb", sa.Float(), nullable=True),
        sa.Column("race_day_hrv_status", sa.String(), nullable=True),
        sa.Column("race_day_recovery_score", sa.Float(), nullable=True),
        sa.Column("race_day_weight", sa.Float(), nullable=True),
        sa.Column("avg_pace_sec_km", sa.Float(), nullable=True),
        sa.Column("splits", sa.JSON(), nullable=True),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id"),
    )
    op.add_column("activities", sa.Column("is_race", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("activities", sa.Column("sub_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "sub_type")
    op.drop_column("activities", "is_race")
    op.drop_table("races")
    # ### end Alembic commands ###
