"""add_garmin_phase1c_tables

Revision ID: 6e99dae5f51e
Revises: e7c9472a2dfc
Create Date: 2026-04-11 17:57:42.478478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e99dae5f51e"
down_revision: Union[str, None] = "e7c9472a2dfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garmin_abnormal_hr_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp_gmt", sa.String(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("hr_value", sa.Integer(), nullable=True),
        sa.Column("threshold_value", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "timestamp_gmt", name="uq_garmin_abnormal_hr_user_ts"),
    )
    op.create_table(
        "garmin_bio_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("lactate_threshold_hr", sa.Integer(), nullable=True),
        sa.Column("lactate_threshold_speed", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_bio_user_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("garmin_bio_metrics")
    op.drop_table("garmin_abnormal_hr_events")
    # ### end Alembic commands ###
