"""add_training_log_is_race

Revision ID: 883ad6dc7748
Revises: 6c5f6ae05c97
Create Date: 2026-04-12 18:13:19.680694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "883ad6dc7748"
down_revision: Union[str, None] = "6c5f6ae05c97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("training_log", sa.Column("is_race", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_log", "is_race")
    # ### end Alembic commands ###
