"""empty message

Revision ID: 8f0a3e515e76
Revises: df1bc1b90aa6
Create Date: 2026-03-22 17:23:33.853778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f0a3e515e76"
down_revision: Union[str, None] = "df1bc1b90aa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scheduled_workouts", sa.Column("planned_duration_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduled_workouts", "planned_duration_seconds")
    # ### end Alembic commands ###
