"""add star_transactions table

Revision ID: 93682f3cf782
Revises: s9b0c1d2e3f4
Create Date: 2026-04-14 15:29:09.535498

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93682f3cf782"
down_revision: Union[str, None] = "s9b0c1d2e3f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("charge_id", sa.String(), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("charge_id"),
    )
    op.create_index(op.f("ix_star_transactions_created_at"), "star_transactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_star_transactions_user_id"), "star_transactions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_star_transactions_user_id"), table_name="star_transactions")
    op.drop_index(op.f("ix_star_transactions_created_at"), table_name="star_transactions")
    op.drop_table("star_transactions")
    # ### end Alembic commands ###
