"""Add progression_model_runs table

Revision ID: 9f31b33412f8
Revises: 9f899b0e09b2
Create Date: 2026-04-19 07:57:14.342433

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f31b33412f8"
down_revision: Union[str, None] = "9f899b0e09b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progression_model_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=16), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n_examples", sa.Integer(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("r2", sa.Float(), nullable=True),
        sa.Column("model_path", sa.String(length=200), nullable=True),
        sa.Column("shap_global_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "sport", "trained_at", name="uq_progression_user_sport_trained"),
    )
    op.create_index(op.f("ix_progression_model_runs_user_id"), "progression_model_runs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_progression_model_runs_user_id"), table_name="progression_model_runs")
    op.drop_table("progression_model_runs")
    # ### end Alembic commands ###
