"""Add source column to activities

Revision ID: 9f899b0e09b2
Revises: d6b75d6b3374
Create Date: 2026-04-18 14:19:24.126122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f899b0e09b2"
down_revision: Union[str, None] = "d6b75d6b3374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "source")
    # ### end Alembic commands ###
