"""add users last_donation_at

Revision ID: ad411cd63317
Revises: 93682f3cf782
Create Date: 2026-04-14 16:46:08.314909

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad411cd63317"
down_revision: Union[str, None] = "93682f3cf782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_donation_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_donation_at")
    # ### end Alembic commands ###
