"""add intervals oauth fields to users

Revision ID: bf0f29e83f2a
Revises: ad411cd63317
Create Date: 2026-04-15 15:53:45.079975

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf0f29e83f2a"
down_revision: Union[str, None] = "ad411cd63317"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("users", sa.Column("intervals_access_token_encrypted", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("intervals_oauth_scope", sa.String(), nullable=True))
    # server_default 'api_key' so existing rows don't break NOT NULL constraint
    # on upgrade; new rows will use the Python-level default from the ORM.
    op.add_column(
        "users",
        sa.Column("intervals_auth_method", sa.String(length=10), nullable=False, server_default="api_key"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "intervals_auth_method")
    op.drop_column("users", "intervals_oauth_scope")
    op.drop_column("users", "intervals_access_token_encrypted")
    # ### end Alembic commands ###
