"""add_race_plans

Revision ID: c3c3d4e5f6a7
Revises: z6a7b8c9d0e1
Create Date: 2026-05-06 21:30:00.000000

Backend storage for race-execution plans generated by the
``generate_race_plan`` MCP tool (see END-63 / END-62).

Schema notes:
- ``goal_id`` references ``athlete_goals.id`` (RACE_A/B/C target rows), not
  ``races.id`` (post-race log keyed on ``activity_id``). The issue spec says
  "race_id FK -> races.id" but ``races`` is the COMPLETED-race table — we plan
  for upcoming events that live in ``athlete_goals``. Naming follows the
  existing ``races.goal_id`` precedent.
- ``payload`` is JSONB so we can index into the structured plan later
  (e.g. surface "fueling.carbs_g_per_hour" trends across plans).
- Idempotency: at most one plan per (goal_id, day-of-generation) — guarded by
  a partial unique index over ``(generated_at AT TIME ZONE 'UTC')::date``,
  which is IMMUTABLE so it's index-safe. NULL goal_id (ad-hoc plans) is not
  deduplicated.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3c3d4e5f6a7"
down_revision: Union[str, None] = "z6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "race_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["goal_id"], ["athlete_goals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_race_plans_user_id", "race_plans", ["user_id"])
    op.create_index("ix_race_plans_goal_id", "race_plans", ["goal_id"])
    op.create_index(
        "ix_race_plans_user_generated",
        "race_plans",
        ["user_id", sa.text("generated_at DESC")],
    )
    # Idempotency: at most one plan per (goal_id, UTC day of generation).
    # Partial — ad-hoc plans (goal_id IS NULL) are not deduplicated here.
    op.execute(
        "CREATE UNIQUE INDEX uq_race_plans_goal_day "
        "ON race_plans (goal_id, ((generated_at AT TIME ZONE 'UTC')::date)) "
        "WHERE goal_id IS NOT NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_race_plans_goal_day")
    op.drop_index("ix_race_plans_user_generated", table_name="race_plans")
    op.drop_index("ix_race_plans_goal_id", table_name="race_plans")
    op.drop_index("ix_race_plans_user_id", table_name="race_plans")
    op.drop_table("race_plans")
