"""Add zone boundary columns to athlete_settings

Revision ID: c6103f687387
Revises: bf0f29e83f2a
Create Date: 2026-04-16 19:58:18.650491

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6103f687387"
down_revision: Union[str, None] = "bf0f29e83f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("athlete_settings", sa.Column("hr_zones", sa.JSON(), nullable=True))
    op.add_column("athlete_settings", sa.Column("hr_zone_names", sa.JSON(), nullable=True))
    op.add_column("athlete_settings", sa.Column("power_zones", sa.JSON(), nullable=True))
    op.add_column("athlete_settings", sa.Column("pace_zones", sa.JSON(), nullable=True))
    op.add_column("athlete_settings", sa.Column("pace_zone_names", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athlete_settings", "pace_zone_names")
    op.drop_column("athlete_settings", "pace_zones")
    op.drop_column("athlete_settings", "power_zones")
    op.drop_column("athlete_settings", "hr_zone_names")
    op.drop_column("athlete_settings", "hr_zones")
    # ### end Alembic commands ###
