"""add_garmin_phase1a_tables

Revision ID: d5bc6b452bd1
Revises: eab8010ef579
Create Date: 2026-04-11 15:17:12.491739

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5bc6b452bd1"
down_revision: Union[str, None] = "eab8010ef579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garmin_daily_summary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("total_distance_m", sa.Float(), nullable=True),
        sa.Column("total_calories", sa.Integer(), nullable=True),
        sa.Column("active_calories", sa.Integer(), nullable=True),
        sa.Column("floors_ascended_m", sa.Float(), nullable=True),
        sa.Column("highly_active_secs", sa.Integer(), nullable=True),
        sa.Column("active_secs", sa.Integer(), nullable=True),
        sa.Column("min_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("avg_stress", sa.Integer(), nullable=True),
        sa.Column("max_stress", sa.Integer(), nullable=True),
        sa.Column("stress_high_secs", sa.Integer(), nullable=True),
        sa.Column("stress_medium_secs", sa.Integer(), nullable=True),
        sa.Column("stress_low_secs", sa.Integer(), nullable=True),
        sa.Column("stress_rest_secs", sa.Integer(), nullable=True),
        sa.Column("body_battery_high", sa.Integer(), nullable=True),
        sa.Column("body_battery_low", sa.Integer(), nullable=True),
        sa.Column("body_battery_charged", sa.Integer(), nullable=True),
        sa.Column("body_battery_drained", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_daily_user_date"),
    )
    op.create_table(
        "garmin_health_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("hrv_value", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_lower", sa.Float(), nullable=True),
        sa.Column("hrv_baseline_upper", sa.Float(), nullable=True),
        sa.Column("hrv_status", sa.String(), nullable=True),
        sa.Column("hr_value", sa.Float(), nullable=True),
        sa.Column("hr_baseline_lower", sa.Float(), nullable=True),
        sa.Column("hr_baseline_upper", sa.Float(), nullable=True),
        sa.Column("hr_status", sa.String(), nullable=True),
        sa.Column("spo2_value", sa.Float(), nullable=True),
        sa.Column("spo2_baseline_lower", sa.Float(), nullable=True),
        sa.Column("spo2_baseline_upper", sa.Float(), nullable=True),
        sa.Column("spo2_status", sa.String(), nullable=True),
        sa.Column("skin_temp_value", sa.Float(), nullable=True),
        sa.Column("skin_temp_baseline_lower", sa.Float(), nullable=True),
        sa.Column("skin_temp_baseline_upper", sa.Float(), nullable=True),
        sa.Column("skin_temp_status", sa.String(), nullable=True),
        sa.Column("respiration_value", sa.Float(), nullable=True),
        sa.Column("respiration_baseline_lower", sa.Float(), nullable=True),
        sa.Column("respiration_baseline_upper", sa.Float(), nullable=True),
        sa.Column("respiration_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_health_user_date"),
    )
    op.create_table(
        "garmin_sleep",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("sleep_start_gmt", sa.String(), nullable=True),
        sa.Column("sleep_end_gmt", sa.String(), nullable=True),
        sa.Column("deep_sleep_secs", sa.Integer(), nullable=True),
        sa.Column("light_sleep_secs", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_secs", sa.Integer(), nullable=True),
        sa.Column("awake_sleep_secs", sa.Integer(), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("duration_score", sa.Integer(), nullable=True),
        sa.Column("recovery_score", sa.Integer(), nullable=True),
        sa.Column("deep_score", sa.Integer(), nullable=True),
        sa.Column("rem_score", sa.Integer(), nullable=True),
        sa.Column("restfulness_score", sa.Integer(), nullable=True),
        sa.Column("avg_respiration", sa.Float(), nullable=True),
        sa.Column("lowest_respiration", sa.Float(), nullable=True),
        sa.Column("highest_respiration", sa.Float(), nullable=True),
        sa.Column("avg_sleep_stress", sa.Float(), nullable=True),
        sa.Column("awake_count", sa.Integer(), nullable=True),
        sa.Column("restless_moments", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_sleep_user_date"),
    )
    op.create_table(
        "garmin_training_readiness",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("timestamp_gmt", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("feedback_short", sa.String(), nullable=True),
        sa.Column("feedback_long", sa.Text(), nullable=True),
        sa.Column("sleep_score_factor_pct", sa.Float(), nullable=True),
        sa.Column("recovery_time", sa.Integer(), nullable=True),
        sa.Column("recovery_factor_pct", sa.Float(), nullable=True),
        sa.Column("acwr_factor_pct", sa.Float(), nullable=True),
        sa.Column("stress_history_factor_pct", sa.Float(), nullable=True),
        sa.Column("hrv_factor_pct", sa.Float(), nullable=True),
        sa.Column("sleep_history_factor_pct", sa.Float(), nullable=True),
        sa.Column("hrv_weekly_avg", sa.Float(), nullable=True),
        sa.Column("acute_load", sa.Float(), nullable=True),
        sa.Column("input_context", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", "input_context", name="uq_garmin_readiness_user_date_ctx"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("garmin_training_readiness")
    op.drop_table("garmin_sleep")
    op.drop_table("garmin_health_status")
    op.drop_table("garmin_daily_summary")
    # ### end Alembic commands ###
