"""empty message

Revision ID: d6f7466de9db
Revises: f0d2f435b802
Create Date: 2026-04-01 17:47:56.090427

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6f7466de9db"
down_revision: Union[str, None] = "f0d2f435b802"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_start_date"), table_name="activities")
    op.drop_index(op.f("idx_ai_workouts_date"), table_name="ai_workouts")
    op.drop_index(op.f("idx_training_log_date"), table_name="training_log")
    op.drop_index(op.f("idx_training_log_source"), table_name="training_log")
    op.drop_index(op.f("idx_workout_cards_date"), table_name="workout_cards")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_workout_cards_date"), "workout_cards", ["date"], unique=False)
    op.create_index(op.f("idx_training_log_source"), "training_log", ["source"], unique=False)
    op.create_index(op.f("idx_training_log_date"), "training_log", ["date"], unique=False)
    op.create_index(op.f("idx_ai_workouts_date"), "ai_workouts", ["date"], unique=False)
    op.create_index(op.f("ix_activities_start_date"), "activities", ["start_date_local"], unique=False)
    # ### end Alembic commands ###
