"""add hrv level1 and recovery columns, activities, workouts, tss tables

Revision ID: df1bc1b90aa6
Revises: 001
Create Date: 2026-03-22 09:27:53.438306

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df1bc1b90aa6"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("sport", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("avg_power", sa.Float(), nullable=True),
        sa.Column("norm_power", sa.Float(), nullable=True),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.Column("ess", sa.Float(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_index(op.f("ix_activities_date"), "activities", ["date"], unique=False)
    op.create_table(
        "scheduled_workouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scheduled_date", sa.String(), nullable=False),
        sa.Column("sport", sa.String(), nullable=False),
        sa.Column("workout_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("planned_tss", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_workouts_scheduled_date"), "scheduled_workouts", ["scheduled_date"], unique=False
    )
    op.create_table(
        "tss_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("sport", sa.String(), nullable=False),
        sa.Column("tss", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tss_history_date"), "tss_history", ["date"], unique=False)
    op.add_column("daily_metrics", sa.Column("body_battery", sa.Integer(), nullable=True))
    op.add_column("daily_metrics", sa.Column("resting_hr", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("stress_score", sa.Integer(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_rmssd_last", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_mean_7d", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_sd_7d", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_lower_bound", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_upper_bound", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_cv_7d", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_swc", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_status", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_days_available", sa.Integer(), nullable=True))
    op.add_column("daily_metrics", sa.Column("hrv_algorithm", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("rhr_status", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("rhr_lower_bound", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("rhr_upper_bound", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ctl", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("atl", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("tsb", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ctl_swim", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ctl_bike", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ctl_run", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ess_today", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("banister_recovery", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("recovery_score", sa.Float(), nullable=True))
    op.add_column("daily_metrics", sa.Column("recovery_category", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("recovery_recommendation", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("readiness_score", sa.Integer(), nullable=True))
    op.add_column("daily_metrics", sa.Column("readiness_level", sa.String(), nullable=True))
    op.add_column("daily_metrics", sa.Column("ai_recommendation", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_metrics", "ai_recommendation")
    op.drop_column("daily_metrics", "readiness_level")
    op.drop_column("daily_metrics", "readiness_score")
    op.drop_column("daily_metrics", "recovery_recommendation")
    op.drop_column("daily_metrics", "recovery_category")
    op.drop_column("daily_metrics", "recovery_score")
    op.drop_column("daily_metrics", "banister_recovery")
    op.drop_column("daily_metrics", "ess_today")
    op.drop_column("daily_metrics", "ctl_run")
    op.drop_column("daily_metrics", "ctl_bike")
    op.drop_column("daily_metrics", "ctl_swim")
    op.drop_column("daily_metrics", "tsb")
    op.drop_column("daily_metrics", "atl")
    op.drop_column("daily_metrics", "ctl")
    op.drop_column("daily_metrics", "rhr_upper_bound")
    op.drop_column("daily_metrics", "rhr_lower_bound")
    op.drop_column("daily_metrics", "rhr_status")
    op.drop_column("daily_metrics", "hrv_algorithm")
    op.drop_column("daily_metrics", "hrv_days_available")
    op.drop_column("daily_metrics", "hrv_status")
    op.drop_column("daily_metrics", "hrv_swc")
    op.drop_column("daily_metrics", "hrv_cv_7d")
    op.drop_column("daily_metrics", "hrv_upper_bound")
    op.drop_column("daily_metrics", "hrv_lower_bound")
    op.drop_column("daily_metrics", "hrv_sd_7d")
    op.drop_column("daily_metrics", "hrv_mean_7d")
    op.drop_column("daily_metrics", "hrv_rmssd_last")
    op.drop_column("daily_metrics", "stress_score")
    op.drop_column("daily_metrics", "resting_hr")
    op.drop_column("daily_metrics", "body_battery")
    op.drop_index(op.f("ix_tss_history_date"), table_name="tss_history")
    op.drop_table("tss_history")
    op.drop_index(op.f("ix_scheduled_workouts_scheduled_date"), table_name="scheduled_workouts")
    op.drop_table("scheduled_workouts")
    op.drop_index(op.f("ix_activities_date"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
