"""add_garmin_phase1b_tables

Revision ID: e7c9472a2dfc
Revises: d5bc6b452bd1
Create Date: 2026-04-11 17:49:23.688128

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c9472a2dfc"
down_revision: Union[str, None] = "d5bc6b452bd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garmin_fitness_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("vo2max_running", sa.Float(), nullable=True),
        sa.Column("vo2max_cycling", sa.Float(), nullable=True),
        sa.Column("endurance_score", sa.Float(), nullable=True),
        sa.Column("max_met", sa.Float(), nullable=True),
        sa.Column("fitness_age", sa.Integer(), nullable=True),
        sa.Column("source_activity_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_fitness_user_date"),
    )
    op.create_table(
        "garmin_race_predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("prediction_5k_secs", sa.Integer(), nullable=True),
        sa.Column("prediction_10k_secs", sa.Integer(), nullable=True),
        sa.Column("prediction_half_secs", sa.Integer(), nullable=True),
        sa.Column("prediction_marathon_secs", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_race_user_date"),
    )
    op.create_table(
        "garmin_training_load",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calendar_date", sa.String(), nullable=False),
        sa.Column("acute_load", sa.Float(), nullable=True),
        sa.Column("chronic_load", sa.Float(), nullable=True),
        sa.Column("acwr", sa.Float(), nullable=True),
        sa.Column("acwr_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "calendar_date", name="uq_garmin_load_user_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("garmin_training_load")
    op.drop_table("garmin_race_predictions")
    op.drop_table("garmin_fitness_metrics")
    # ### end Alembic commands ###
