"""add fit_file_path to activities

Revision ID: e9b364e82eb8
Revises: d6f7466de9db
Create Date: 2026-04-04 14:42:37.202551

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9b364e82eb8"
down_revision: Union[str, None] = "d6f7466de9db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("fit_file_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "fit_file_path")
    # ### end Alembic commands ###
