"""restore_date_indexes

Revision ID: fb59b4bef745
Revises: e3f50cc7c33d
Create Date: 2026-04-08 17:29:20.658453

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb59b4bef745"
down_revision: Union[str, None] = "e3f50cc7c33d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_activities_start_date_local"), "activities", ["start_date_local"], unique=False)
    op.create_index(op.f("ix_ai_workouts_date"), "ai_workouts", ["date"], unique=False)
    op.create_index(op.f("ix_training_log_date"), "training_log", ["date"], unique=False)
    op.create_index(op.f("ix_workout_cards_date"), "workout_cards", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_cards_date"), table_name="workout_cards")
    op.drop_index(op.f("ix_training_log_date"), table_name="training_log")
    op.drop_index(op.f("ix_ai_workouts_date"), table_name="ai_workouts")
    op.drop_index(op.f("ix_activities_start_date_local"), table_name="activities")
    # ### end Alembic commands ###
