"""Race-execution plans generated by the ``generate_race_plan`` MCP tool.

Stores a structured plan (warmup, per-leg pacing corridors, fueling,
contingencies) for an upcoming race. The plan is regenerated on demand —
idempotent at the (goal_id, UTC day) level via a partial unique index, so
calling generate twice in the same day returns the existing row instead of
piling up duplicates.

See END-63 / migration ``v2c3d4e5f6a7_add_race_plans.py``.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from data.db.common import Base, Session
from data.db.decorator import dual


class RacePlan(Base):
    __tablename__ = "race_plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    # FK to athlete_goals.id (RACE_A/B/C target rows). Nullable for ad-hoc /
    # experimental plans that aren't bound to a saved goal yet. See migration
    # docstring for why this is goal_id and not race_id.
    goal_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("athlete_goals.id", ondelete="SET NULL"), nullable=True, index=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    model_version: Mapped[str] = mapped_column(String(64), nullable=False)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # --- CRUD ---

    @classmethod
    @dual
    def save(
        cls,
        *,
        user_id: int,
        goal_id: int | None,
        model_version: str,
        payload: dict,
        session: Session,
    ) -> RacePlan:
        """Persist a newly generated plan and return the row.

        Note: idempotency at the (goal_id, day) level is enforced by the
        partial unique index ``uq_race_plans_goal_day``. Callers that want
        the "already generated today" behavior should call
        :meth:`get_today_for_goal` first.
        """
        row = cls(
            user_id=user_id,
            goal_id=goal_id,
            generated_at=datetime.now(timezone.utc),
            model_version=model_version,
            payload=payload,
        )
        session.add(row)
        session.commit()
        return row

    @classmethod
    @dual
    def get_latest_for_race(cls, goal_id: int, *, session: Session) -> RacePlan | None:
        """Return the most recent plan for a goal (highest generated_at)."""
        result = session.execute(
            select(cls).where(cls.goal_id == goal_id).order_by(cls.generated_at.desc()).limit(1)
        )
        return result.scalar_one_or_none()

    @classmethod
    @dual
    def get_today_for_goal(cls, goal_id: int, *, session: Session) -> RacePlan | None:
        """Return today's plan (UTC day) for a goal, or None.

        Mirrors the partial unique index ``uq_race_plans_goal_day`` so callers
        can skip a fresh generation when one already exists for today.
        """
        today = datetime.now(timezone.utc).date()
        result = session.execute(
            select(cls)
            .where(
                cls.goal_id == goal_id,
                cls.generated_at >= datetime(today.year, today.month, today.day, tzinfo=timezone.utc),
            )
            .order_by(cls.generated_at.desc())
            .limit(1)
        )
        return result.scalar_one_or_none()

    @classmethod
    @dual
    def get_for_user_recent(cls, user_id: int, limit: int = 10, *, session: Session) -> list[RacePlan]:
        """Return the user's most recent plans, newest first."""
        result = session.execute(
            select(cls).where(cls.user_id == user_id).order_by(cls.generated_at.desc()).limit(limit)
        )
        return list(result.scalars().all())
