"""Race-execution plans generated by the ``generate_race_plan`` MCP tool.

Stores a structured plan (warmup, per-leg pacing corridors, fueling,
contingencies) for an upcoming race. The plan is regenerated on demand —
idempotent at the (goal_id, UTC day) level via a partial unique index, so
calling generate twice in the same day returns the existing row instead of
piling up duplicates.

See END-63 / migration ``c3c3d4e5f6a7_add_race_plans.py``.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from data.db.common import Base, Session
from data.db.decorator import dual


class RacePlan(Base):
    __tablename__ = "race_plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    # FK to athlete_goals.id (RACE_A/B/C target rows). Nullable for ad-hoc /
    # experimental plans that aren't bound to a saved goal yet. See migration
    # docstring for why this is goal_id and not race_id.
    goal_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("athlete_goals.id", ondelete="SET NULL"), nullable=True, index=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    model_version: Mapped[str] = mapped_column(String(64), nullable=False)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # --- CRUD ---

    @classmethod
    @dual
    def save(
        cls,
        *,
        user_id: int,
        goal_id: int | None,
        model_version: str,
        payload: dict,
        session: Session,
    ) -> RacePlan:
        """Persist a newly generated plan and return the row.

        Note: idempotency at the (goal_id, day) level is enforced by the
        partial unique index ``uq_race_plans_goal_day``. Callers that want
        the "already generated today" behavior should call
        :meth:`get_today_for_goal` first.

        **Returned-row caveat (review M1, 2026-05-09):** the session that wrote
        the row closes when ``@with_session`` exits, so the returned ORM
        instance is detached. Loaded scalar columns (``id`` / ``model_version``
        / ``payload`` / ``generated_at``) stay accessible thanks to
        ``expire_on_commit=False`` (set globally, see ``data/db/common.py``);
        ``session.refresh(row)`` below populates DB-side defaults before
        detachment. Lazy-loaded relationships (none today on RacePlan, but
        future ``row.user`` / ``row.goal`` would need this) WILL raise
        ``DetachedInstanceError`` — return a DTO instead if/when that's
        added. ``with_session`` doesn't own commit in this codebase, so the
        ORM method must commit itself.
        """
        row = cls(
            user_id=user_id,
            goal_id=goal_id,
            generated_at=datetime.now(timezone.utc),
            model_version=model_version,
            payload=payload,
        )
        session.add(row)
        session.commit()
        session.refresh(row)
        return row

    @classmethod
    @dual
    def get_latest_for_race(cls, goal_id: int, *, user_id: int, session: Session) -> RacePlan | None:
        """Return the most recent plan for a goal (highest generated_at).

        Scoped to ``user_id`` as defense-in-depth — callers already vet
        ownership of ``goal_id``, but a leaked id would otherwise cross-tenant
        read here. Mirrors the pattern in
        ``data/db/athlete.py:362-407`` (``deactivate_by_id`` / ``set_ctl_target``).
        """
        result = session.execute(
            select(cls).where(cls.goal_id == goal_id, cls.user_id == user_id).order_by(cls.generated_at.desc()).limit(1)
        )
        return result.scalar_one_or_none()

    @classmethod
    @dual
    def get_today_for_goal(cls, goal_id: int, *, user_id: int, session: Session) -> RacePlan | None:
        """Return today's plan (UTC day) for a goal, or None.

        Mirrors the partial unique index ``uq_race_plans_goal_day`` so callers
        can skip a fresh generation when one already exists for today. Scoped
        to ``user_id`` as defense-in-depth.

        Range is half-open ``[today_utc, tomorrow_utc)`` rather than just
        ``>= today_utc``: the ``order_by(...).limit(1)`` shape masks an upper
        bound today, but a future caller using ``count()`` or returning all
        rows would otherwise leak future-day plans (PR2.3 in-place
        UPDATE bumps generated_at, so a regen on day N+1 of an N-day row
        would still appear in the day-N query). See review L1 (2026-05-09).
        """
        today = datetime.now(timezone.utc).date()
        today_start = datetime(today.year, today.month, today.day, tzinfo=timezone.utc)
        tomorrow_start = today_start + timedelta(days=1)
        result = session.execute(
            select(cls)
            .where(
                cls.goal_id == goal_id,
                cls.user_id == user_id,
                cls.generated_at >= today_start,
                cls.generated_at < tomorrow_start,
            )
            .order_by(cls.generated_at.desc())
            .limit(1)
        )
        return result.scalar_one_or_none()

    @classmethod
    @dual
    def update_in_place(
        cls,
        plan_id: int,
        *,
        user_id: int,
        model_version: str,
        payload: dict,
        session: Session,
    ) -> RacePlan | None:
        """Force-regenerate path: overwrite an existing row's payload + bump
        ``generated_at`` + ``model_version``. Preserves the row's ``id`` so
        external references (Telegram deep-links) stay stable across regens.

        Spec RACE_PLAN_SPEC §7: regenerate uses in-place UPDATE rather than
        DELETE+INSERT specifically to keep ids stable. Caller is responsible
        for the rate-limit check (see ``data/race_plan_service.py``); this
        method just performs the write.

        Scoped to ``user_id`` for defense-in-depth — same pattern as
        ``get_latest_for_race`` / ``get_today_for_goal``. Returns the updated
        row, or ``None`` if no matching row exists for this user.
        """
        row = session.execute(select(cls).where(cls.id == plan_id, cls.user_id == user_id)).scalar_one_or_none()
        if row is None:
            return None
        row.payload = payload
        row.model_version = model_version
        row.generated_at = datetime.now(timezone.utc)
        session.commit()
        session.refresh(row)
        return row

    @classmethod
    @dual
    def mark_pushed_for_race_date(
        cls,
        plan_id: int,
        race_date: str,
        *,
        user_id: int,
        session: Session,
    ) -> bool:
        """Stamp ``payload.pushed_for_race_date`` so the 24h pre-race push
        actor short-circuits on retry / cron re-fire (PR2.6).

        Idempotency key is ``race_date`` (ISO ``YYYY-MM-DD``), not just a
        boolean — handles the edge case where a goal is rescheduled and the
        athlete should get a NEW push for the new date.

        Does NOT touch ``generated_at`` (that would either bump the partial
        unique index into a new day or interfere with the regen rate-limit
        counter — see ``update_in_place`` for the comparison). Returns
        ``True`` if the row was actually marked, ``False`` if no matching
        row (defensive: actor caller has already loaded ``plan_row``, so
        a False here only happens on a parallel delete during the actor run).
        """
        row = session.execute(select(cls).where(cls.id == plan_id, cls.user_id == user_id)).scalar_one_or_none()
        if row is None:
            return False
        # JSONB columns need a fresh dict to trigger SQLAlchemy change-detection;
        # mutating in place won't dirty the attribute. See data/db/wellness.py
        # for the same pattern.
        row.payload = {**(row.payload or {}), "pushed_for_race_date": race_date}
        session.commit()
        return True
